-- [VIII] SEQUENCE ; 순차번호 생성기, 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9999
  MINVALUE 1
  NOCACHE
  NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
  NUM  NUMBER(4) PRIMARY KEY, -- 시퀀스 이용
  NAME VARCHAR2(30) NOT NULL,
  TEL  VARCHAR2(20) UNIQUE,
  ADDRESS VARCHAR2(100),
  LAST_MODIFYED DATE DEFAULT SYSDATE);
  
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
  VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울시 마포구'); -- 몇번 
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
  VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999', '서울시 서대문구구');
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
  VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-8888-8888', '서울시 영등포구');
SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀀스 값
COMMIT;

-- EX	초기값101부터 최대값999,999까지 1씩 증가하는 test_seq 시퀀스를 생성하라
DROP SEQUENCE TEST_SEQ;
CREATE SEQUENCE TEST_SEQ
  START WITH 101
  MAXVALUE 999999
  NOCACHE
  NOCYCLE;
SELECT TEST_SEQ.NEXTVAL FROM DUAL;
SELECT TEST_SEQ.CURRVAL FROM DUAL;

-- 총 연습문제 1
DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;
DROP SEQUENCE CUS_SQ;
CREATE TABLE CUS_LEVEL(
    LEVELNO   NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);
CREATE SEQUENCE CUS_SQ MAXVALUE 999999 NOCACHE NOCYCLE;
CREATE TABLE CUSTOMER(
    CNO      NUMBER(6)    PRIMARY KEY,
    CNAME    VARCHAR2(50) NOT NULL,
    JOINDATE DATE         DEFAULT SYSDATE,
    PHONE    VARCHAR2(30) UNIQUE,
    POINT    NUMBER(10),
    LEVELNO  NUMBER(1)    REFERENCES CUS_LEVEL(LEVELNO));
INSERT INTO CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4, 'BLACK');
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, '홍길동', 
        TO_DATE('21/06/10','RR/MM/DD'),'010-9999-9999',300,1);
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, '이철수', 
        TO_DATE('20/11/12','RR/MM/DD'),'010-8888-8888',NULL,2);
SELECT * FROM CUSTOMER;
-- TEST
SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD'), 
                    PHONE, POINT, LEVELNAME
    FROM CUS_LEVEL L, CUSTOMER C
    WHERE L.LEVELNO=C.LEVELNO;
