--[XI] 인덱스 : 주키가 아닌 필드 중심으로 조회를 많이 하는 경우 조회속도 향상
SELECT * FROM USER_INDEXES; -- 'SCOTT'계정이 소유한 인덱스 정보
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP;
SELECT * FROM EMP01;
INSERT INTO EMP01 SELECT * FROM EMP01; -- 1번(28개) 2번(56개)
SELECT COUNT(*) FROM EMP01;
INSERT INTO EMP01 SELECT * FROM EMP01; -- 12번(22만개)
SELECT TO_CHAR(COUNT(*),'9,999,999') FROM EMP01;
INSERT INTO EMP01 (EMPNO, ENAME, DEPTNO) VALUES (1111, 'HONG', 40);
INSERT INTO EMP01 SELECT * FROM EMP01; -- 3번(180만개)
SELECT TO_CHAR(COUNT(*),'9,999,999') FROM EMP01;
-- 인덱스 생성 전 조회 속도 ; 0.04초
SELECT * FROM EMP01 WHERE ENAME='HONG';
CREATE INDEX IDX_EMP01_ENAME  ON EMP01(ENAME); -- 인덱스 생성
-- 인덱스 생성 후 조회 속도 ; 0.001초
SELECT * FROM EMP01 WHERE ENAME='HONG';
SELECT * FROM USER_INDEXES WHERE INDEX_NAME='IDX_EMP01_ENAME';
DROP INDEX IDX_EMP01_ENAME;
SELECT * FROM EMP01 WHERE ENAME='HONG'; -- 0.052초


